name: buildScript
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check
      uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v2
      
    - name: build and deploy
      run:
        python3 build.py

    - name: add and commit
      uses: EndBug/add-and-commit@v7
      with: 
        author_name: jingfelix
        branch: main
        message: latest build
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
