name: buildScript
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check
      uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v2
      
    - name: build
      run: |
        pip install -i https://test.pypi.org/simple/ html-jingfelix==0.0.3a0
        pip install markdown
        python3 build.py

    - name: Get current time
      uses: gerred/actions/current-time@master
      id: current-time

    - name: add to main branch
      uses: EndBug/add-and-commit@v7
      with:
        author_name: jingfelix
        branch: main
        message: ${{ steps.current-time.outputs.time }} build
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1